core/src/main/java/com/graphhopper/reader/dem/EdgeElevationInterpolator.java

Disables distance recalculation of interpolated edges. The reason for this change is that the edge distance computation in ORS does not consider elevation data anyway, so the edge length is not expected to change. A proper implementation allowing for setting a method for doing the distance calculation would require a lot of changes and and is beyond our current scope.

Changes required by GIScience/openrouteservice#750

---

core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/util/DefaultSpeedCalculator.java
core/src/main/java/com/graphhopper/routing/weighting/TimeDependentFastestWeighting.java

Decouple `TimeDependentFastestWeighting` from `ConditionalSpeedCalculator` in order to be able to use it with flag encoders which don't store OSM conditional speeds.

Check for conditional access and speed encoders

---

core/src/main/java/com/graphhopper/reader/ConditionalInspector.java
core/src/main/java/com/graphhopper/reader/ConditionalTagInspector.java
core/src/main/java/com/graphhopper/reader/osm/conditional/ConditionalOSMSpeedInspector.java
core/src/main/java/com/graphhopper/reader/osm/conditional/ConditionalOSMTagInspector.java
core/src/main/java/com/graphhopper/reader/osm/conditional/ConditionalParser.java
core/src/main/java/com/graphhopper/routing/TDAStar.java
core/src/main/java/com/graphhopper/routing/util/AbstractFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/ConditionalAccessEdgeFilter.java
core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
core/src/main/java/com/graphhopper/routing/util/TimeDependentAccessEdgeFilter.java
core/src/main/java/com/graphhopper/routing/util/TimeDependentConditionalEvaluator.java
core/src/main/java/com/graphhopper/routing/weighting/TimeDependentAccessWeighting.java
core/src/test/java/com/graphhopper/reader/osm/conditional/ConditionalOSMSpeedInspectorTest.java
core/src/test/java/com/graphhopper/reader/osm/conditional/ConditionalOSMTagInspectorTest.java
core/src/test/java/com/graphhopper/reader/osm/conditional/ConditionalParserTest.java
core/src/test/java/com/graphhopper/routing/util/ConditionalAccessTest.java
core/src/test/java/com/graphhopper/routing/util/TimeDependentAccessEdgeFilterTest.java
reader-osm/src/main/java/com/graphhopper/reader/osm/OSMReader.java

Addresses https://github.com/GIScience/openrouteservice/issues/827 by restoring the original way of handling conditional access restrictions. Now edges with time-dependent access restrictions are not only marked as lazy-evaluated, but their default access is being evaluated at graph build time as well. The default value determined at graph build time can then be used for non time-dependent routing.

Resolve default access of conditional edges at graph build time

---

core/src/main/java/com/graphhopper/reader/dem/CGIARProvider.java

fixes https://github.com/GIScience/openrouteservice/issues/845, https://github.com/GIScience/openrouteservice/issues/839
fixes #34 
When I tried locally it gave me `NullPointerException` when building ORS with patched GH:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project openrouteservice: Fatal error compiling: CompilerException: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project openrouteservice: Fatal error compiling
```
But I'm a bit rusty here as well..

change to https URL for CGIAR

---

core/src/main/java/com/graphhopper/routing/Dijkstra.java
core/src/main/java/com/graphhopper/routing/Path.java
core/src/main/java/com/graphhopper/routing/TDDijkstra.java

Use the `reverseDirection` parameter to make goal to start Dijkstra. Necessary for reversible (time dependent) isochrones.

Use reverseDirection parameter for Dijkstra and TDDijkstra

---

core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/InstructionsFromEdges.java
core/src/main/java/com/graphhopper/routing/Path.java
core/src/main/java/com/graphhopper/routing/PathBidirRef.java
core/src/main/java/com/graphhopper/routing/TDAStar.java
core/src/main/java/com/graphhopper/routing/TDDijkstra.java
core/src/main/java/com/graphhopper/routing/ch/Path4CH.java
core/src/main/java/com/graphhopper/routing/util/AccessEdgeFilter.java
core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/CarFlagEncoder.java
core/src/main/java/com/graphhopper/routing/util/ConditionalAccessEdgeFilter.java
core/src/main/java/com/graphhopper/routing/util/ConditionalSpeedCalculator.java
core/src/main/java/com/graphhopper/routing/util/EncodingManager.java
core/src/main/java/com/graphhopper/routing/util/TimeDependentAccessEdgeFilter.java
core/src/main/java/com/graphhopper/storage/ConditionalEdges.java
core/src/main/java/com/graphhopper/storage/ConditionalEdgesMap.java
core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
core/src/test/java/com/graphhopper/routing/util/ConditionalAccessTest.java
reader-osm/src/main/java/com/graphhopper/reader/osm/OSMReader.java

This update features the following two major changes:
- Introduces the logic to create extended storage for OSM conditional access and speed only if the flag encoder for a given profile has the corresponding encoders initialized. This is necessary in order to disable the use of conditionals during time-dependent routing in ORS.
- Fixes the behavior of avoiding recalculation of edge times when generating instructions. This is achieved by storing the times computed by the path processor in an array which is then passed over to the instructions processor.

Allow conditionals to be optional

---

core/src/main/java/com/graphhopper/GraphHopper.java

As computing landmarks might depend on traffic data, a hook is introduced to inject traffic preprocessing before landmark preparations.

Hook to enable traffic matching before computing landmarks

---

core/pom.xml
pom.xml
reader-osm/pom.xml

use log4j 2.15.0 which addresses CVE https://nvd.nist.gov/vuln/detail/CVE-2021-44228

update log4j version to address CVE

---

reader-osm/src/main/java/com/graphhopper/reader/osm/OSMReader.java
reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java

Changes necessary for creating additional edges in ORS which facilitate routing over open spaces, see https://github.com/GIScience/openrouteservice/pull/1187.

Make selected methods in OSMReader public

---

core/src/main/java/com/graphhopper/GraphHopper.java

Overriding the method in ORS facilitates modifying the weighting which is being used to prepare CH graphs. This allows, for example, setting of the default HGV vehicle type.
This is a necessary prerequisite for the fix addressing some of the routing issues uncovered by the benchmarks.

fix: enable overriding of `initCHPreparationHandler`

---

core/src/main/java/com/graphhopper/routing/weighting/FastestWeighting.java

Use speed calculator rather than average speed encoder to obtain edge speed in order to be able to modify edge speed at query time. This is necessary when used with traffic data or when queried with maximum speed parameter.

fix: obtain speed from `speedCalculator` in `fastestWeighting`

---

core/src/main/java/com/graphhopper/util/DateTimeHelper.java

Avoid running into problems in case time zone map has not been initialized.

Use default time zone in case of uninitialized time zone map

---

core/src/main/java/com/graphhopper/routing/lm/LMRoutingAlgorithmFactory.java

Add missing time-dependent bit to `LMRoutingAlgorithmFactory`.

Enable time-dependent A* with LM approximation

---

core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java

flushing and reloading conditional access and speed data hadn't been working, causing ors tests to fail on reloading graphs. Code has been taken from the "Time-dependent routing" PR against 0.13
fixes #61

fix: persist conditional access and speed

---

core/pom.xml

The current version several CVEs and needs a forced upgrade to version 3.22.3.

fix(pom,cve): Upgrade protobuf to the latest version

---

core/pom.xml

The current version several CVEs and needs a forced upgrade to version 1.23.0.

fix(pom,cve): Upgrade commons-compress to 1.23.0

---

core/pom.xml

The current version several CVEs and needs a forced upgrade to version 2.8.

fix(pom,cve): Upgrade xmlgraphics-commons to 2.8

---

core/pom.xml
core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java
core/src/main/java/com/graphhopper/util/DateTimeHelper.java
core/src/test/java/com/graphhopper/routing/util/TimeDependentAccessEdgeFilterTest.java
web/pom.xml

dustinj.timezonemap is not maintained anymore and introduces more and more vulnerabilities. At the moment we anyway only support one time zone. The removal should therefore not break anything. If more timezones should be reported, we need a better implementation anyways.

fix(cve): Remove dustinj.timezonemap due to CVEs

---

README.md
client-hc/README.md
client-hc/pom.xml
core/pom.xml
example/pom.xml
hmm-lib/pom.xml
map-matching/README.md
map-matching/pom.xml
navigation/pom.xml
pom.xml
reader-gtfs/pom.xml
tools/pom.xml
web-api/pom.xml
web-bundle/pom.xml
web/pom.xml

fix(pom): Rename the project

---

core/pom.xml
hmm-lib/pom.xml

Currently, the hmm-lib module is still build in compatibility mode. Let's fix this.

fix: Replace java compile target with the default defined version

---

core/src/main/java/com/graphhopper/routing/Router.java

Use a common time parameter which is set upstream only when the algorithm actually requires it.
Required by https://github.com/GIScience/openrouteservice/pull/1871.

fix: passing of time to routing algorithms

---

core/pom.xml

currently used version of protobuf-java has vulnerability CWE-121 / CVE-2024-7254 / CVSS 8.7

fix: update protobuf-java

---

core/src/main/java/com/graphhopper/routing/util/FerrySpeedCalculator.java
core/src/test/java/com/graphhopper/routing/util/FerrySpeedCalculatorTest.java

Prevents falling back to penalized `unknown_speed` value of 5 km/h in case `duration` tag is not present yet there is a `maxspeed` tag available, see [examples](https://overpass-turbo.eu/s/20lk).
This fix has been motivated by https://github.com/GIScience/openrouteservice/issues/620.

fix: consider OSM `maxspeed` tag in speed estimation for ferry-type routes
