reader-osm/src/main/java/com/graphhopper/reader/osm/OSMReader.java

Added ability to specify the tags that information should be stored against the nodes

Ors node tags on way

---

core/src/main/java/com/graphhopper/GHRequest.java
core/src/main/java/com/graphhopper/routing/AStarBidirection.java
core/src/main/java/com/graphhopper/routing/Dijkstra.java
core/src/main/java/com/graphhopper/routing/DijkstraBidirectionRef.java
core/src/main/java/com/graphhopper/routing/EdgeIteratorStateHelper.java
core/src/main/java/com/graphhopper/routing/InstructionsFromEdges.java
core/src/main/java/com/graphhopper/routing/Path.java
core/src/main/java/com/graphhopper/routing/PathProcessingContext.java
core/src/main/java/com/graphhopper/routing/VirtualEdgeIterator.java
core/src/main/java/com/graphhopper/routing/VirtualEdgeIteratorState.java
core/src/main/java/com/graphhopper/routing/util/PathProcessor.java
core/src/main/java/com/graphhopper/routing/weighting/TurnWeighting.java
core/src/main/java/com/graphhopper/storage/BaseGraph.java
core/src/main/java/com/graphhopper/storage/SPTEntry.java
core/src/main/java/com/graphhopper/util/EdgeIteratorState.java
core/src/main/java/com/graphhopper/util/GHUtility.java
core/src/main/java/com/graphhopper/util/InstructionAnnotation.java
core/src/main/java/com/graphhopper/util/PathMerger.java

- getOriginalEdge() handling moved to own class
- removed WayType
- removed deviation from bearing
- removed remaining 'simplyGeometry'
- removed remaining 'pathIndex'

more ors 0.10.1 simplifications

---

core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/weighting/ConsistentWeightApproximator.java
core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
core/src/main/java/com/graphhopper/storage/GraphBuilder.java
core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java

Took all changes from ors_core_alt and put them into a clone of ors_0.10.1. Now merging back so we do not need a ors_core_alt anymore.

Add core-alt stuff to 0.10 branch

---

core/src/main/java/com/graphhopper/GraphHopper.java

To give dynamic control for geometry simplification via query parameter!

public access to GH geometry simplify function

---

core/src/main/java/com/graphhopper/routing/AStarBidirection.java
core/src/main/java/com/graphhopper/routing/lm/LMApproximator.java
core/src/test/java/com/graphhopper/routing/lm/PrepareLandmarksTest.java

Fixes https://github.com/GIScience/graphhopper/issues/21.

Patch ALT to find optimal routes

---

core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/weighting/ConsistentWeightApproximator.java
core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
core/src/main/java/com/graphhopper/storage/GraphBuilder.java
core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java

Adds annotations to changes introduces when implementing CALT.
Closes #20.

Annotate CALT-specific modifications to the fork

---

core/src/main/java/com/graphhopper/routing/AlternativeRoute.java
core/src/main/java/com/graphhopper/routing/RoutingAlgorithmFactorySimple.java

required for restrictions with alternative route. changes should be completely safe for everything else.

apply edge filter to alternative route algorithm

---

core/src/main/java/com/graphhopper/reader/dem/CGIARProvider.java

Fixes https://github.com/GIScience/openrouteservice/issues/394

change CGIAR URL to the latest available one

---

core/src/main/java/com/graphhopper/storage/GraphHopperStorage.java

Get CH graph necessary for fast isochrone algorithm.

Add isocore graph retrieval

---

CONTRIBUTORS.md
core/src/main/java/com/graphhopper/GraphHopper.java

* fix sort memory usage
* fix github user name

reduce memory usage after sorting graph (#1755)

---

core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/template/AlternativeRoutingTemplate.java
core/src/main/java/com/graphhopper/util/PathMerger.java

enable passing multiple ExtraInfoProcessors to the PassMerger, required for alternative routes algo

alternative_routes extra info fix

---

core/src/main/java/com/graphhopper/routing/PathTDCore.java
core/src/main/java/com/graphhopper/routing/VirtualEdgeIterator.java
core/src/main/java/com/graphhopper/routing/VirtualEdgeIteratorState.java
core/src/main/java/com/graphhopper/routing/ch/PreparationWeighting.java
core/src/main/java/com/graphhopper/storage/CHGraph.java
core/src/main/java/com/graphhopper/storage/CHGraphImpl.java
core/src/main/java/com/graphhopper/util/CHEdgeIteratorState.java
core/src/main/java/com/graphhopper/util/GHUtility.java

Adjustments to accommodate time-dependent core routing algorithms.

Time-dependent core routing

---

core/src/main/java/com/graphhopper/reader/osm/conditional/ConditionalParser.java
core/src/main/java/com/graphhopper/routing/util/ConditionalSpeedCalculator.java
core/src/main/java/com/graphhopper/routing/util/TimeDependentAccessEdgeFilter.java
pom.xml

Fixes build errors due to outdated third-party libs.

Update OSM conditional parser libraries

---

core/src/main/java/com/graphhopper/routing/util/AbstractFlagEncoder.java
reader-osm/src/main/java/com/graphhopper/reader/osm/OSMReader.java

See https://github.com/GIScience/openrouteservice/pull/1046.

Use exact geometry-based way distance for computing ferry speed

---

pom.xml

repo causing timeout during build

remove bintray

---

core/src/main/java/com/graphhopper/reader/ReaderElement.java

Needed by the [fix](https://github.com/GIScience/openrouteservice/pull/1291) addressing https://github.com/GIScience/openrouteservice/issues/1219.

Methods for handling OSM tags containing enumerations

---

core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/CHPathCalculator.java
core/src/main/java/com/graphhopper/routing/DefaultWeightingFactory.java
core/src/main/java/com/graphhopper/routing/FlexiblePathCalculator.java
core/src/main/java/com/graphhopper/routing/PathCalculator.java
core/src/main/java/com/graphhopper/routing/Router.java
core/src/main/java/com/graphhopper/routing/RoutingAlgorithmFactorySimple.java
core/src/main/java/com/graphhopper/routing/ViaRouting.java

Facilitate TD requests coming from ORS.

Support for time-dependent routing

---

core/src/main/java/com/graphhopper/GraphHopper.java
core/src/main/java/com/graphhopper/routing/lm/LMPreparationHandler.java

Changes to streamline traffic-enabled routing.

fix: move postprocessing hook

---

.github/workflows/run_maven_tests.yml

fix(workflow): Run test workflows on every PR to ors_4.0

---

.github/workflows/run_maven_tests.yml

fix(workflow): Escape the branch naming

---

core/src/main/java/com/graphhopper/routing/DefaultWeightingFactory.java

There is no need for all the injection points anymore because ORS now directly implements `WeightingFactory`.
Can be merged as soon as https://github.com/GIScience/openrouteservice/pull/1412 is merged.

Restore original weighting factory

---

.github/workflows/push-packages.yml
pom.xml

* Update `<distributionManagement>` in pom.xml
* Update GitHub Workflow for deploying artifacts

update pom.xml and GitHub workflow to deploy to new repo

---

.github/workflows/push-packages.yml
pom.xml

(cherry picked from commit d1493d03dac28ef2700f57409f48777ab2f9fe6e)

update pom.xml and GitHub workflow to deploy to new repo (#91)

---

core/pom.xml
hmm-lib/pom.xml
pom.xml

dropwizard-dependencies, commons-compress, janino, ConditionalRestrictionParser, OpeningHoursParser, log4j

fix: update dependencies 

---

core/src/main/java/com/graphhopper/routing/weighting/custom/CustomModelParser.java
web-api/src/main/java/com/graphhopper/jackson/StatementDeserializer.java

- fix CustomModelParser to compile speed/priority statements
- make StatementDeserializer public

Ors 4.0 custom model

---

core/src/main/java/com/graphhopper/routing/util/FerrySpeedCalculator.java
core/src/test/java/com/graphhopper/routing/util/FerrySpeedCalculatorTest.java

Addresses https://github.com/GIScience/openrouteservice/issues/2030.

fix: maxspeed tag for ferries
